begin: 1666787318.9887888
cmd: /opt/fio/bin/fio --name="libaio-xnvme" --rw="randread" --size="12G" --iodepth="128"
  --bs="512" --direct="1" --thread="1" --time_based="1" --runtime="7" --ramp_time="3"
  --norandommap="1" --allow_file_create="0" --ioengine="external:/usr/local/lib/x86_64-linux-gnu/libxnvme-fio-engine.so"
  --xnvme_be="linux" --xnvme_async="libaio" --xnvme_sync="nvme" --xnvme_admin="nvme"
  --xnvme_dev_nsid="1" --filename="/dev/nvme0n1" --output-format="normal,json" --output="/tmp/fio-output_512_128_libaio-xnvme_0.txt"
  --cpus_allowed="1"
cwd: None
elapsed: 11.083345651626587
end: 1666787330.0721345
err: 0
output_dpath: /home/safl/git/spdkvf2022/cijoe-output/003_fio
output_fpath: /home/safl/git/spdkvf2022/cijoe-output/003_fio/cmd_65.output
